"""crear tablas pedidos y carrito

Revision ID: 2165d8a65590
Revises: 7d80d0dda99e
Create Date: 2026-08-05 18:35:40.079049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2165d8a65590'
down_revision: Union[str, Sequence[str], None] = '7d80d0dda99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
