"""agregar stock a productos

Revision ID: 2d2b3456a0c2
Revises: 2683b52b8961
Create Date: 2026-08-10 12:53:11.492074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2b3456a0c2'
down_revision: Union[str, Sequence[str], None] = '2683b52b8961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'stock')
    # ### end Alembic commands ###
